# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('BookName', models.CharField(max_length=100)),
                ('BookAuthor', models.CharField(max_length=100)),
                ('BookIntroduction', models.CharField(max_length=2000)),
                ('DownNum', models.IntegerField(default=0)),
                ('PushNum', models.IntegerField(default=0)),
                ('ImgAdd', models.CharField(max_length=200)),
                ('BookPublishTime', models.CharField(max_length=50, null=True)),
                ('catalog', models.CharField(max_length=4000, null=True)),
                ('pages', models.CharField(max_length=50, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('author_intro', models.CharField(max_length=4000, null=True)),
                ('rating', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=10, null=True)),
                ('zan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField()),
                ('BookType', models.CharField(max_length=50, null=True)),
                ('TypeImage', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=7000)),
                ('CommentTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField(null=True)),
                ('User', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=7000)),
                ('CommentTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('BookId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('User', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PushBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField()),
                ('SendUser', models.CharField(max_length=50)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('BookId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('UpUser', models.CharField(max_length=50)),
                ('FileName', models.CharField(max_length=300)),
                ('FileAdd', models.FileField(upload_to='./static/book')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('LoginTime', models.TimeField(auto_now=True)),
                ('RegisterTime', models.TimeField(auto_now_add=True)),
                ('Integral', models.IntegerField(default=0, null=True)),
                ('HeadImg', models.FileField(null=True, upload_to=b'')),
                ('Other_Info', models.TextField(null=True)),
            ],
        ),
    ]
