# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Zan',
            field=models.IntegerField(null=True),
        ),
    ]
