# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_comment_zan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Zan',
            field=models.IntegerField(default=0),
        ),
    ]
