# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20170111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='CommentTime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
