# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20170112_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='LoginTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='RegisterTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
